name: formatter

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.2.1
        with:
          node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: check package
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline
      - name: check formatt
        run: yarn run prettier
