name: formatter

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get node version from volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@main
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.2.1
        with:
        node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: check package
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        runs: yarn install --prefer-offline
      - name: check formatt
        runs: yarn run prettier